### ISSUE TITLE
Use character name instead of player name for RP

### ISSUE THREAD

**Issue by MountainRat** [kibook/poodlechat#1]
I love this script, but my issue with it is it only shows player IDs instead of character IDs. For roleplay, I think it would be better to show the ID of whatever character from the database is being used. Is there anyway you could implement this? Or maybe show me where in the code I can update it to call the character name instead of player name? Thanks!

**Comment by kibook** [comment]
What framework do you use for the character names? If it's a very common one, I might look into adding a configuration option to toggle displaying character names vs. player names.

If you wanted to add it yourself, I'd start by looking at every occurrence of the function `GetPlayerName` in the code, particularly in [server/server.lua](https://github.com/kibook/poodlechat/blob/master/server/server.lua). Replace this with something like `GetCharacterName` which fetches the player's current character name from your database.

**Comment by MountainRat** [comment]
I use VORP, which is becoming a popular framework.

**Comment by kibook** [comment]
Added an official option in 0b93ac4.

Uncomment `ServerConfig.Framework = 'VORP'` in [server/config.lua](https://github.com/kibook/poodlechat/tree/master/server/config.lua) and it will fetch their first and last name with the VORP API.
