### ISSUE TITLE
[PoodleChat] [error] Failed to initialize: 0 nil []

### ISSUE THREAD

**Issue by achrafhkdk** [kibook/poodlechat#3]
![image](https://user-images.githubusercontent.com/44878760/113659007-11ef7300-9699-11eb-97b3-f57b97331b90.png)

**Comment by kibook** [comment]
429 is the HTTP error code for Too Many Requests, and Discord will respond with that code if you're making requests too fast from the same bot.

Have you modified the ServerConfig.DiscordRateLimit setting? You could try increasing it. If you're using the same bot token  for many things, maybe try creating a new bot with a separate token.
