### ISSUE TITLE
Please add config files to gitignore

### ISSUE THREAD

**Issue by lewk-io** [kibook/poodlechat#7]
Hi,

Please could you put the config files in gitignore so that the repo can be cloned without conflicts?

Cheers

**Comment by kibook** [comment]
I'm not sure that makes sense. The config files will be updated with new default settings as features are added.

If you mean you want to edit the config file and then update with `git pull`, use `git pull --autostash` to pull while preserving your local changes. Or, create your own branch and merge/rebase with master to update it, which will also let you version control your own configuration changes.
